### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/auth#2]
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at ServerResponse.header (/home/michael/cde/hackgt/auth/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/home/michael/cde/hackgt/auth/node_modules/express/lib/response.js:170:12)
    at exports.templateRoutes.route.get (/home/michael/cde/hackgt/auth/server/routes/templates.js:66:14)
    at Layer.handle [as handle_request] (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/layer.js:95:5)
    at /home/michael/cde/hackgt/auth/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/index.js:335:12)
    at next (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/index.js:275:10)
    at Object.<anonymous> (/home/michael/cde/hackgt/auth/server/routes/templates.js:49:9)
    at Generator.next (<anonymous>)
    at /home/michael/cde/hackgt/auth/server/routes/templates.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/home/michael/cde/hackgt/auth/server/routes/templates.js:3:12)
    at exports.templateRoutes.use (/home/michael/cde/hackgt/auth/server/routes/templates.js:31:57)
    at Layer.handle [as handle_request] (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/index.js:317:13)
    at /home/michael/cde/hackgt/auth/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/michael/cde/hackgt/auth/node_modules/express/lib/router/index.js:335:12)
```

function:

```
exports.templateRoutes.route("/login").get((request, response) => {
    const ssoAuth = request.cookies["sso-auth"];
    if (request.isAuthenticated() && ssoAuth === request.sessionID) {
        response.redirect("/success");
    }
    let templateData = {
        siteTitle: common_1.config.eventName,
        error: request.flash("error"),
        success: request.flash("success")
    };
    const callback = request.query.callback;
    if (callback) {
        response.cookie("callback", callback, common_1.COOKIE_OPTIONS);
    }
    response.send(loginTemplate(templateData));
});
```

**Comment by petschekr** [comment]
I think you need to add a return after the redirect because that method sets the headers and body at the same time which then causes `.cookie()` and `.send()` to fail.
